
#ifndef SOCKET_EXAMPLE_SHARED_H
#define SOCKET_EXAMPLE_SHARED_H

#define SERVER_ADDRESS_MAX_LENG 16
#define USERNAME_MAX_LENG 21

#define SERVER_ADDRESS_STR "127.0.0.1"
#define SERVER_PORT 2345

#define STRINGS_ARE_EQUAL( Str1, Str2 ) ( strcmp( (Str1), (Str2) ) == 0 )


#endif // SOCKET_EXAMPLE_SHARED_H